version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stepfunction-webinar-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1thoon2ma0g89"
s3_prefix = "stepfunction-webinar"
region = "ap-south-1"
profile = "stepfunctionwebinar"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
