AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: step-function-webinar
Resources:
  stepFunction1:
    Type: AWS::Serverless::Application
    Properties:
      Location: stepFunction1/template.yaml
  stepFunction2:
    Type: AWS::Serverless::Application
    Properties:
      Location: stepFunction2/template.yaml
  stepFunction3:
    Type: AWS::Serverless::Application
    Properties:
      Location: stepFunction3/template.yaml
  stepFunction4:
    Type: AWS::Serverless::Application
    Properties:
      Location: stepFunction4/template.yaml
    DependsOn: 
      - stepFunction1
      - stepFunction2
      - stepFunction3

